const tasksDB = {
    // Тип 1: Формы глаголов (V2 и V3)
    verbs: {
        "be": { v2: "was/were", v3: "been", translate: "быть", optionsV2: ["was/were", "beed", "were", "was"], optionsV3: ["been", "beed", "bin", "was"] },
        "become": { v2: "became", v3: "become", translate: "становиться", optionsV2: ["became", "becomen", "becomes", "becamee"], optionsV3: ["become", "became", "becomen", "becoming"] },
        "begin": { v2: "began", v3: "begun", translate: "начинать", optionsV2: ["began", "begun", "beginned", "begins"], optionsV3: ["begun", "began", "beginned", "begon"] },
        "break": { v2: "broke", v3: "broken", translate: "ломать", optionsV2: ["broke", "breaked", "broken", "breaks"], optionsV3: ["broken", "broke", "breaken", "broked"] },
        "bring": { v2: "brought", v3: "brought", translate: "приносить", optionsV2: ["brought", "brang", "bringed", "brung"], optionsV3: ["brought", "brung", "bringed", "broughten"] },
        "buy": { v2: "bought", v3: "bought", translate: "покупать", optionsV2: ["bought", "buyed", "boughten", "boughts"], optionsV3: ["bought", "buyed", "boughten", "bin"] },
        "choose": { v2: "chose", v3: "chosen", translate: "выбирать", optionsV2: ["chose", "choosed", "chosen", "chooses"], optionsV3: ["chosen", "chose", "choosed", "choosen"] },
        "do": { v2: "did", v3: "done", translate: "делать", optionsV2: ["did", "done", "doed", "does"], optionsV3: ["done", "did", "doen", "doing"] },
        "drink": { v2: "drank", v3: "drunk", translate: "пить", optionsV2: ["drank", "drunk", "drinked", "drinks"], optionsV3: ["drunk", "drank", "drinken", "drunken"] },
        "drive": { v2: "drove", v3: "driven", translate: "водить", optionsV2: ["drove", "drived", "driven", "droves"], optionsV3: ["driven", "drove", "drivened", "droven"] },
        "eat": { v2: "ate", v3: "eaten", translate: "есть", optionsV2: ["ate", "eaten", "eated", "eats"], optionsV3: ["eaten", "ate", "eatened", "eated"] },
        "fall": { v2: "fell", v3: "fallen", translate: "падать", optionsV2: ["fell", "falled", "fallen", "falls"], optionsV3: ["fallen", "fell", "fallened", "felled"] },
        "get": { v2: "got", v3: "got", translate: "получать", optionsV2: ["got", "getted", "gotten", "gets"], optionsV3: ["got", "gotten", "getted", "gotted"] },
        "give": { v2: "gave", v3: "given", translate: "давать", optionsV2: ["gave", "gived", "given", "gives"], optionsV3: ["given", "gave", "givened", "gived"] },
        "go": { v2: "went", v3: "gone", translate: "идти", optionsV2: ["went", "gone", "goed", "goes"], optionsV3: ["gone", "went", "wenten", "going"] },
        "know": { v2: "knew", v3: "known", translate: "знать", optionsV2: ["knew", "knowed", "known", "knows"], optionsV3: ["known", "knew", "knowen", "knowed"] },
        "make": { v2: "made", v3: "made", translate: "делать", optionsV2: ["made", "maked", "mades", "making"], optionsV3: ["made", "maden", "maked", "making"] },
        "see": { v2: "saw", v3: "seen", translate: "видеть", optionsV2: ["saw", "seen", "seed", "sees"], optionsV3: ["seen", "saw", "seened", "seeing"] },
        "write": { v2: "wrote", v3: "written", translate: "писать", optionsV2: ["wrote", "writed", "written", "writes"], optionsV3: ["written", "wrote", "writen", "wroteen"] },
        "take": { v2: "took", v3: "taken", translate: "брать", optionsV2: ["took", "taked", "taken", "takes"], optionsV3: ["taken", "took", "taked", "takenen"] },
        "read": { v2: "read", v3: "read", translate: "читать", optionsV2: ["read", "readed", "red", "reads"], optionsV3: ["read", "readen", "red", "reading"] },
        "speak": { v2: "spoke", v3: "spoken", translate: "говорить", optionsV2: ["spoke", "speaked", "spaked", "spoken"], optionsV3: ["spoken", "spoke", "speakened", "speaken"] },
        "sleep": { v2: "slept", v3: "slept", translate: "спать", optionsV2: ["slept", "sleeped", "slepped", "sleept"], optionsV3: ["slept", "sleepen", "sleept", "sleeped"] },
        "run": { v2: "ran", v3: "run", translate: "бежать", optionsV2: ["ran", "runned", "run", "rans"], optionsV3: ["run", "ran", "runned", "running"] },
        "swim": { v2: "swam", v3: "swum", translate: "плавать", optionsV2: ["swam", "swum", "swimmed", "swams"], optionsV3: ["swum", "swam", "swimmen", "swimmed"] },
        "fight": { v2: "fought", v3: "fought", translate: "сражаться", optionsV2: ["fought", "fighted", "faught", "foughten"], optionsV3: ["fought", "foughten", "fighted", "faught"] },
        "find": { v2: "found", v3: "found", translate: "находить", optionsV2: ["found", "finded", "founed", "founds"], optionsV3: ["found", "founden", "finded", "founding"] },
        "forget": { v2: "forgot", v3: "forgotten", translate: "забывать", optionsV2: ["forgot", "forgetted", "forgat", "forgots"], optionsV3: ["forgotten", "forgot", "forgetten", "forgat"] },
        "hide": { v2: "hid", v3: "hidden", translate: "прятаться", optionsV2: ["hid", "hided", "hidden", "hides"], optionsV3: ["hidden", "hid", "hiden", "hided"] },
        "leave": { v2: "left", v3: "left", translate: "покидать", optionsV2: ["left", "leaved", "leafed", "leften"], optionsV3: ["left", "leaven", "leaved", "lefting"] },
        "lose": { v2: "lost", v3: "lost", translate: "терять", optionsV2: ["lost", "losed", "loosed", "losten"], optionsV3: ["lost", "losen", "losed", "loosing"] },
        "send": { v2: "sent", v3: "sent", translate: "отправлять", optionsV2: ["sent", "sended", "senden", "sents"], optionsV3: ["sent", "senden", "sended", "sending"] },
        "sing": { v2: "sang", v3: "sung", translate: "петь", optionsV2: ["sang", "sung", "singed", "sangs"], optionsV3: ["sung", "sang", "singen", "singed"] },
        "steal": { v2: "stole", v3: "stolen", translate: "красть", optionsV2: ["stole", "stealed", "stollen", "stales"], optionsV3: ["stolen", "stole", "stealen", "stolenen"] },
        "think": { v2: "thought", v3: "thought", translate: "думать", optionsV2: ["thought", "thinked", "thaught", "thoughten"], optionsV3: ["thought", "thoughten", "thinked", "thaught"] },
        "understand": { v2: "understood", v3: "understood", translate: "понимать", optionsV2: ["understood", "understanded", "understod", "understands"], optionsV3: ["understood", "understanden", "understanded", "understod"] },
        "wear": { v2: "wore", v3: "worn", translate: "носить (одежду)", optionsV2: ["wore", "weared", "ware", "worn"], optionsV3: ["worn", "wore", "wearen", "weared"] },
        "win": { v2: "won", v3: "won", translate: "побеждать", optionsV2: ["won", "winned", "wan", "wins"], optionsV3: ["won", "winnen", "winned", "winning"] },
        "sell": { v2: "sold", v3: "sold", translate: "продавать", optionsV2: ["sold", "selled", "saled", "solds"], optionsV3: ["sold", "solden", "selled", "selling"] },
        "spend": { v2: "spent", v3: "spent", translate: "тратить", optionsV2: ["spent", "spended", "spend", "spents"], optionsV3: ["spent", "spenden", "spended", "spending"] },
        "build": { v2: "built", v3: "built", translate: "строить", optionsV2: ["built", "builded", "builted", "builds"], optionsV3: ["built", "builded", "builten", "building"] },
        "catch": { v2: "caught", v3: "caught", translate: "ловить", optionsV2: ["caught", "catched", "cought", "catchen"], optionsV3: ["caught", "catched", "coughten", "catching"] },
        "cut": { v2: "cut", v3: "cut", translate: "резать", optionsV2: ["cut", "cutted", "cutten", "cuts"], optionsV3: ["cut", "cutten", "cutted", "cutting"] },
        "dig": { v2: "dug", v3: "dug", translate: "копать", optionsV2: ["dug", "digged", "dag", "dugs"], optionsV3: ["dug", "digged", "dugen", "dugged"] },
        "draw": { v2: "drew", v3: "drawn", translate: "рисовать", optionsV2: ["drew", "drawed", "drawn", "drewn"], optionsV3: ["drawn", "drew", "drawed", "drawnen"] },
        "feel": { v2: "felt", v3: "felt", translate: "чувствовать", optionsV2: ["felt", "feeled", "felted", "feels"], optionsV3: ["felt", "feeled", "felten", "feeling"] },
        "fly": { v2: "flew", v3: "flown", translate: "летать", optionsV2: ["flew", "flied", "flown", "flewn"], optionsV3: ["flown", "flew", "flied", "flownen"] },
        "grow": { v2: "grew", v3: "grown", translate: "расти", optionsV2: ["grew", "growed", "grown", "grewn"], optionsV3: ["grown", "grew", "growed", "grownen"] },
        "hold": { v2: "held", v3: "held", translate: "держать", optionsV2: ["held", "holded", "holted", "holds"], optionsV3: ["held", "holden", "holded", "holding"] },
        "keep": { v2: "kept", v3: "kept", translate: "держать/хранить", optionsV2: ["kept", "keeped", "kepped", "keeps"], optionsV3: ["kept", "keeped", "kepten", "keeping"] },
        "lead": { v2: "led", v3: "led", translate: "вести", optionsV2: ["led", "leaded", "lead", "leded"], optionsV3: ["led", "leaded", "leden", "leading"] },
        "meet": { v2: "met", v3: "met", translate: "встречать", optionsV2: ["met", "meeted", "meten", "meets"], optionsV3: ["met", "meten", "meeted", "meeting"] },
        "pay": { v2: "paid", v3: "paid", translate: "платить", optionsV2: ["paid", "payed", "paided", "pays"], optionsV3: ["paid", "payed", "paiden", "paying"] },
        "put": { v2: "put", v3: "put", translate: "класть", optionsV2: ["put", "putted", "putten", "puts"], optionsV3: ["put", "putten", "putted", "putting"] },
        "ride": { v2: "rode", v3: "ridden", translate: "ездить", optionsV2: ["rode", "rided", "ridden", "roden"], optionsV3: ["ridden", "rode", "rided", "riddened"] },
        "ring": { v2: "rang", v3: "rung", translate: "звонить", optionsV2: ["rang", "rung", "ringed", "rangs"], optionsV3: ["rung", "rang", "rungen", "ringed"] },
        "rise": { v2: "rose", v3: "risen", translate: "подниматься", optionsV2: ["rose", "rised", "risen", "rosen"], optionsV3: ["risen", "rose", "rised", "risened"] },
        "shake": { v2: "shook", v3: "shaken", translate: "трясти", optionsV2: ["shook", "shaked", "shaken", "shooks"], optionsV3: ["shaken", "shook", "shaked", "shakened"] },
        "shoot": { v2: "shot", v3: "shot", translate: "стрелять", optionsV2: ["shot", "shooted", "shoten", "shots"], optionsV3: ["shot", "shoten", "shooted", "shooting"] },
        "sit": { v2: "sat", v3: "sat", translate: "сидеть", optionsV2: ["sat", "sitted", "satten", "sits"], optionsV3: ["sat", "satten", "sitted", "sitting"] },
        "play": { v2: "played", v3: "played", translate: "играть", optionsV2: ["played", "playd", "plaied", "play"], optionsV3: ["played", "play", "plaed", "playd"] },
        "study": { v2: "studied", v3: "studied", translate: "изучать, исследовать", optionsV2: ["studied", "studyed", "studed", "studies"], optionsV3: ["studied", "studyed", "studed", "studies"] },
        "stay": { v2: "stayed", v3: "stayed", translate: "оставаться, гостить", optionsV2: ["stayed", "staid", "stayd", "steyed"], optionsV3: ["stayed", "staid", "stayd", "steyed"] },
        "want": { v2: "wanted", v3: "wanted", translate: "хотеть, желать", optionsV2: ["wanted", "wantet", "wantied", "want"], optionsV3: ["wanted", "wantet", "wantied", "want"] },
        "work": { v2: "worked", v3: "worked", translate: "работать", optionsV2: ["worked", "wrought", "workt", "work"], optionsV3: ["worked", "wrought", "workt", "work"] },
        "try": { v2: "tried", v3: "tried", translate: "пытаться", optionsV2: ["tried", "tryed", "trien", "trieded"], optionsV3: ["tried", "tryed", "trien", "trieded"] },
        "talk": { v2: "talked", v3: "talked", translate: "разговаривать, болтать", optionsV2: ["talked", "talkt", "talkedr", "talke"], optionsV3: ["talked", "talkt", "talkedr", "talke"] },
        "live": { v2: "lived", v3: "lived", translate: "жить", optionsV2: ["lived", "live", "liven", "liveded"], optionsV3: ["lived", "live", "liven", "liveded"] },
        "watch": { v2: "watched", v3: "watched", translate: "смотреть", optionsV2: ["watched", "watchd", "wotched", "watch"], optionsV3: ["watched", "watchd", "wotched", "watch"] },
        "clean": { v2: "cleaned", v3: "cleaned", translate: "чистить", optionsV2: ["cleaned", "cleand", "clean", "cleened"], optionsV3: ["cleaned", "cleand", "clean", "cleened"] },
        "walk": { v2: "walked", v3: "walked", translate: "идти", optionsV2: ["walked", "walkt", "walk", "walken"], optionsV3: ["walked", "walkt", "walk", "walken"] },
        "call": { v2: "called", v3: "called", translate: "звонить, звать", optionsV2: ["called", "calld", "calling", "call"], optionsV3: ["called", "calld", "calling", "call"] },
        "cook": { v2: "cooked", v3: "cooked", translate: "готовить", optionsV2: ["cooked", "cuked", "cooken", "cook"], optionsV3: ["cooked", "cuked", "cooken", "cook"] },
        "visit": { v2: "visited", v3: "visited", translate: "навещать", optionsV2: ["visited", "visitied", "visit", "vist"], optionsV3: ["visited", "visitied", "visit", "vist"] },
        "finish": { v2: "finished", v3: "finished", translate: "заканчивать", optionsV2: ["finished", "finishd", "fined", "finish"], optionsV3: ["finished", "finishd", "fined", "finish"] },
        "wash": { v2: "washed", v3: "washed", translate: "мыть", optionsV2: ["washed", "washd", "washen", "wash"], optionsV3: ["washed", "washd", "washen", "wash"] },
        "listen": { v2: "listened", v3: "listened", translate: "слушать", optionsV2: ["listened", "listend", "listeneded", "listen"], optionsV3: ["listened", "listend", "listeneded", "listen"] },
        "use": { v2: "used", v3: "used", translate: "пользоваться, использовать", optionsV2: ["used", "useed", "usied", "use"], optionsV3: ["used", "useed", "usied", "use"] },
        "arrive": { v2: "arrived", v3: "arrived", translate: "прибывать", optionsV2: ["arrived", "arived", "arrievd", "arrive"], optionsV3: ["arrived", "arived", "arrievd", "arrive"] },
        "look": { v2: "looked", v3: "looked", translate: "смотреть", optionsV2: ["looked", "lookt", "look", "looken"], optionsV3: ["looked", "lookt", "look", "looken"] },
        "invite": { v2: "invited", v3: "invited", translate: "приглашать", optionsV2: ["invited", "inviteed", "inviteded", "invate"], optionsV3: ["invited", "inviteed", "inviteded", "invate"] },
        "laugh": { v2: "laughed", v3: "laughed", translate: "смеяться", optionsV2: ["laughed", "laughd", "laughen", "laugh"], optionsV3: ["laughed", "laughd", "laughen", "laugh"] },
        "start": { v2: "started", v3: "started", translate: "начинать", optionsV2: ["started", "startet", "startd", "start"], optionsV3: ["started", "startet", "startd", "start"] },
        "answer": { v2: "answered", v3: "answered", translate: "отвечать", optionsV2: ["answered", "answerd", "answerred", "answer"], optionsV3: ["answered", "answerd", "answerred", "answer"] },
        "cry": { v2: "cried", v3: "cried", translate: "кричать, плакать", optionsV2: ["cried", "cryed", "crieded", "crye"], optionsV3: ["cried", "cryed", "crieded", "crye"] },
        "open": { v2: "opened", v3: "opened", translate: "открывать", optionsV2: ["opened", "opend", "openen", "open"], optionsV3: ["opened", "opend", "openen", "open"] },
        "help": { v2: "helped", v3: "helped", translate: "помогать", optionsV2: ["helped", "helpped", "helpen", "help"], optionsV3: ["helped", "helpped", "helpen", "help"] },
        "found": { v2: "founded", v3: "founded", translate: "основывать", optionsV2: ["founded", "found", "foundet", "foundied"], optionsV3: ["founded", "found", "foundet", "foundied"] },
        "like": { v2: "liked", v3: "liked", translate: "нравиться", optionsV2: ["liked", "likeed", "likd", "like"], optionsV3: ["liked", "likeed", "likd", "like"] },
        "move": { v2: "moved", v3: "moved", translate: "двигаться, передвигаться", optionsV2: ["moved", "moveed", "movd", "move"], optionsV3: ["moved", "moveed", "movd", "move"] },
        "bake": { v2: "baked", v3: "baked", translate: "печь", optionsV2: ["baked", "bakeed", "bakt", "bake"], optionsV3: ["baked", "bakeed", "bakt", "bake"] },
        "ask": { v2: "asked", v3: "asked", translate: "просить", optionsV2: ["asked", "askd", "asking", "ask"], optionsV3: ["asked", "askd", "asking", "ask"] }
    },

    // Тип 2: Пропуски
    sentences: [
        { text: "I have ___ a secret treasure chest.", options: ["found", "find", "finded", "founden"], answer: "found" },
        { text: "You must ___ your health before the boss fight.", options: ["restore", "restored", "restoring", "restores"], answer: "restore" },
        { text: "We ___ through the Dark Forest for three days.", options: ["walked", "walk", "walking", "walks"], answer: "walked" },
        { text: "The wizard ___ a spell to open the ancient gate.", options: ["casts", "cast", "casting", "caster"], answer: "casts" },
        { text: "The dragon is ___ above the mountains.", options: ["flying", "fly", "flew", "flown"], answer: "flying" },
        { text: "The rogue ___ quietly through the dungeon.", options: ["sneaks", "sneak", "sneaking", "sneaked"], answer: "sneaks" },
        { text: "The healer ___ a potion to the wounded hero.", options: ["gives", "give", "giving", "given"], answer: "gives" },
        { text: "The party must ___ the bridge before the trolls arrive.", options: ["cross", "crosses", "crossing", "crossed"], answer: "cross" },
        { text: "The adventurer ___ a torch in the dark cave.", options: ["lights", "light", "lighting", "lit"], answer: "lights" },
        { text: "The goblins are ___ the treasure chest.", options: ["guarding", "guard", "guards", "guarded"], answer: "guarding" },
        { text: "The knight must ___ the princess from the tower.", options: ["rescue", "rescues", "rescued", "rescuing"], answer: "rescue" },
        { text: "The wizard ___ ancient runes on the stone.", options: ["reads", "read", "reading", "reader"], answer: "reads" },
        { text: "The dragon ___ on a mountain of gold.", options: ["sleeps", "sleep", "sleeping", "slept"], answer: "sleeps" },
        { text: "The hero is ___ through the forest.", options: ["traveling", "travel", "traveled", "travels"], answer: "traveling" },
        { text: "They ___ the ancient map before setting sail.", options: ["studied", "study", "studies", "studying"], answer: "studied" },
        { text: "The bard ___ a sad tune about the lost city.", options: ["sings", "sing", "sang", "sung"], answer: "sings" },
        { text: "Our party ___ camp by the river tonight.", options: ["will make", "make", "made", "making"], answer: "will make" },  
        { text: "The gates ___ as the king's banner was raised.", options: ["opened", "open", "opens", "opening"], answer: "opened" }
    ],


    // Тип 3: Диалоги
    dialogues: [
        { q: "Where is the Ancient Artifact hidden?", options: ["In the deep cave.", "I like apples.", "Tomorrow morning.", "It is blue."], answer: "In the deep cave." },
        { q: "Who is the ruler of this kingdom?", options: ["King Arthur.", "A simple farmer.", "A dangerous wolf.", "The blacksmith."], answer: "King Arthur." },
        { q: "Do you have enough mana to teleport?", options: ["Yes, I do.", "I am a cat!", "I have a sword.", "It is far away."], answer: "Yes, I do." },
        { q: "What happened to the lost squad?", options: ["They were defeated.", "A have a sword.", "It is a big city.", "I am a mage."], answer: "They were defeated." },
        { q: "Where can we find the dragon's treasure?", options: ["In the old mountain.", "I drink water.", "My boots are red.", "It is very small."], answer: "In the old mountain." },
        { q: "Who guards the northern gate?", options: ["A brave knight.", "Three oranges.", "My sister.", "A wooden table."], answer: "A brave knight." },
        { q: "Do you know the secret spell?", options: ["Yes, I know it.", "The bread is hot.", "My horse is fast.", "It is under the bed."], answer: "Yes, I know it." },
        { q: "What is in the wizard's tower?", options: ["Ancient books.", "Two sandwiches.", "A yellow hat.", "My old shoes."], answer: "Ancient books." },
        { q: "What do we need to open the magic door?", options: ["A silver key.", "A blue pillow.", "Hot soup.", "A wooden spoon."], answer: "A silver key." },
        { q: "Where is the hidden dungeon entrance?", options: ["Behind the waterfall.", "I eat bread.", "My cloak is warm.", "The stone is round."], answer: "Behind the waterfall." },
        { q: "Who lives in the enchanted forest?", options: ["A wise elf.", "A broken chair.", "A loud bell.", "A cold stone."], answer: "A wise elf." },
        { q: "What do we need to defeat the dark lord?", options: ["A legendary sword.", "A cup of tea.", "A small coin.", "A green apple."], answer: "A legendary sword." },
        { q: "Who can heal the wounded hero?", options: ["A forest druid.", "A lazy dog.", "A big rock.", "A red apple."], answer: "A forest druid." },
        { q: "Do you hear the dragon approaching?", options: ["Yes, I hear it.", "I like milk.", "My boots are clean.", "It is very cold."], answer: "Yes, I hear it." },
        { q: "Who forged the magic armor?", options: ["A master blacksmith.", "A tiny mouse.", "A green leaf.", "A silent cloud."], answer: "A master blacksmith." },
        { q: "Where is the path to the hidden valley?", options: ["Through the dark woods.", "Under the table.", "Inside a box.", "On my hat."], answer: "Through the dark woods." },
        { q: "Who stole the royal crown?", options: ["A sneaky thief.", "A blue chair.", "A small fish.", "A glass bottle."], answer: "A sneaky thief." },
        { q: "What do we need to summon the spirit?", options: ["A magic rune.", "A spoon.", "A red shoe.", "A paper box."], answer: "A magic rune." },
        { q: "Who leads the army of light?", options: ["A noble paladin.", "A sleepy cat.", "A wooden stick.", "A white box."], answer: "A noble paladin." }

    ]
};